增加副站长
ariespan-Open/ariespan-log pull request #15
Opened 2022-08-28 16:32 UTC by majinqiawa

网站第二负责人/副站长：majinqi（QQ2193132609）

Signed-off-by: majinqi <13818406990@163.com>

2022-08-28 16:32 UTC, majinqiawa commented
很好

2022-08-29 00:35 UTC, Dedicatus5457 requested changes
commit不规范

2022-08-29 00:45 UTC, Dedicatus5457 commented
算了我帮你改罢你也不会用git。。。

2022-08-29 03:32 UTC, Dedicatus5457 submitted a review, later dismissed

2022-08-29 03:38 UTC, Dedicatus5457 approved these changes

2022-08-29 03:39 UTC, merged